#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DoubleGaugeAndroid.Resource", IsApplication=true)]

namespace DoubleGaugeAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Com.Syncfusion.Gauges.Resource.Dimension.pading_bottom = global::DoubleGaugeAndroid.Resource.Dimension.pading_bottom;
			global::Com.Syncfusion.Gauges.Resource.Dimension.pading_top = global::DoubleGaugeAndroid.Resource.Dimension.pading_top;
			global::Com.Syncfusion.Gauges.Resource.Id.eightsegment = global::DoubleGaugeAndroid.Resource.Id.eightsegment;
			global::Com.Syncfusion.Gauges.Resource.Id.fourteensegment = global::DoubleGaugeAndroid.Resource.Id.fourteensegment;
			global::Com.Syncfusion.Gauges.Resource.Id.rootLayout = global::DoubleGaugeAndroid.Resource.Id.rootLayout;
			global::Com.Syncfusion.Gauges.Resource.Id.sevensegment = global::DoubleGaugeAndroid.Resource.Id.sevensegment;
			global::Com.Syncfusion.Gauges.Resource.Id.sixteensegment = global::DoubleGaugeAndroid.Resource.Id.sixteensegment;
			global::Com.Syncfusion.Gauges.Resource.Layout.circulargauge_layout = global::DoubleGaugeAndroid.Resource.Layout.circulargauge_layout;
			global::Com.Syncfusion.Gauges.Resource.Layout.digitalgauge_layout = global::DoubleGaugeAndroid.Resource.Layout.digitalgauge_layout;
			global::Com.Syncfusion.Gauges.Resource.String.ApplicationName = global::DoubleGaugeAndroid.Resource.String.ApplicationName;
			global::Com.Syncfusion.Gauges.Resource.String.Hello = global::DoubleGaugeAndroid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f030001
			public const int pading_bottom = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int pading_top = 2130903040;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int eightsegment = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int fourteensegment = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int rootLayout = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int sevensegment = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int sixteensegment = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int circulargauge_layout = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int digitalgauge_layout = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Main = 2130837506;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
